// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnLbrd40moRdnBFrH6Xx_byvwqGBbJfY',
    appId: '1:164533537164:web:2437eb1f16a2c6432e2ea9',
    messagingSenderId: '164533537164',
    projectId: 'myweatherapp-99350',
    authDomain: 'myweatherapp-99350.firebaseapp.com',
    storageBucket: 'myweatherapp-99350.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxIp5jzHxkyfAKZyBskp3YSUqqPplAhMI',
    appId: '1:164533537164:android:1e9eadac51a80a912e2ea9',
    messagingSenderId: '164533537164',
    projectId: 'myweatherapp-99350',
    storageBucket: 'myweatherapp-99350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPKvtGBPtSY8xP_2S6Yxr_OEnlhG8kuQ',
    appId: '1:164533537164:ios:17e254fe58ac6dce2e2ea9',
    messagingSenderId: '164533537164',
    projectId: 'myweatherapp-99350',
    storageBucket: 'myweatherapp-99350.appspot.com',
    iosClientId: '164533537164-r54coaq3704jbd835248oscqrgdq7goa.apps.googleusercontent.com',
    iosBundleId: 'com.example.myweatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEPKvtGBPtSY8xP_2S6Yxr_OEnlhG8kuQ',
    appId: '1:164533537164:ios:17e254fe58ac6dce2e2ea9',
    messagingSenderId: '164533537164',
    projectId: 'myweatherapp-99350',
    storageBucket: 'myweatherapp-99350.appspot.com',
    iosClientId: '164533537164-r54coaq3704jbd835248oscqrgdq7goa.apps.googleusercontent.com',
    iosBundleId: 'com.example.myweatherapp',
  );
}
